repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: "v5.10.1"
      hooks:
          - id: isort
            types: [file, python]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            types: [file, python]
            additional_dependencies: ["regex==2021.9.30"]
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies:
                [
                    "flake8-comprehensions",
                    "flake8-debugger",
                    "flake8-mutable",
                ]
